name: mobile_assesment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  internet_connection_checker: ^2.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/Cheese Burger.jpg
    - assets/images/Image Burger.jpg
    - assets/images/welcome.jpeg
    # - assets/images/
    # - assets/images/
    # - assets/images/
    # - assets/images/
    # - assets/images/
    # - assets/images/
    # - assets/images/


